### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by pbelskiy** [pbelskiy/quickbuild#9]
- [x] Get API Version
- [x] Interact with Audits
- [x] Interact with Configurations
- [x] Interact with Builds
- [x] Interact with Latest Builds
- [x] Interact with Build Requests
- [x] Trigger Build via GET Request
- [x] Interact with Users
- [x] Interact with Groups
- [x] Interact with Group Memberships
- [x] Interact with Dashboards
- [x] Interact with Group Share
- [x] Interact with User Share
- [x] Interact with Cloud Profiles
- [x] Interact with Configuration Authorizations
- [x] Interact with Resources
- [x] Interact with Agent Tokens
- [x] Get System Attributes of Grid Node
- [x] Get and Set User Attributes of Grid Node
- [x] Interact with Reports
- [x] Interact with Changes
- [x] Interact with Issues
- [x] Query Build Notifications
- [x] Query Grid Measurements
- [x] Access Information of Published Files
- [x] Interact with Build Agents
- [x] Backup Database
- [x] Pause System
- [x] Resume System
- [x] Check System Pause Information
- [x] Retrieve Object Identifier

**Comment by pbelskiy** [comment]
https://wiki.pmease.com/display/QB10/RESTful+API

**Comment by pbelskiy** [comment]
+ reports (0.13)

**Comment by pbelskiy** [comment]
- nodes (0.14)

**Comment by pbelskiy** [comment]
- authorizations (0.15)

**Comment by pbelskiy** [comment]
- cloud profiles (0.16)
